models:
  - name: "gpt-4o"
    provider: "openai"
    model_id: "gpt-4o"
    code_name: "Alpha"
    enabled: true
  - name: "claude-3.5-sonnet"
    provider: "openrouter"
    model_id: "anthropic/claude-3.5-sonnet"
    code_name: "Beta"
    enabled: true
  - name: "gemini-1.5-pro"
    provider: "openrouter"
    model_id: "google/gemini-1.5-pro"
    code_name: "Gamma"
    enabled: true
  - name: "deepseek-r1"
    provider: "openrouter"
    model_id: "deepseek/deepseek-r1"
    code_name: "Delta"
    enabled: false
  - name: "llama-3.1-405b"
    provider: "openrouter"
    model_id: "meta-llama/llama-3.1-405b-instruct"
    code_name: "Epsilon"
    enabled: false

settings:
  max_models: 3  # How many models to consult simultaneously
  parallel_timeout: 120  # Timeout for parallel calls in seconds
  synthesis_model_selection: "random"  # "random" or "first" or "best_performer"
  log_level: "INFO"

api_keys:
  openai_api_key: "${OPENAI_API_KEY}"
  openrouter_api_key: "${OPENROUTER_API_KEY}" 